### ISSUE TITLE
Support for fs2 v3 and Cats v3

### ISSUE THREAD

**Issue by rehanone** [regis-leray/fs2-ftp#131]
Is there a plan to migrate this library to support fs2 v3 and Cats v3?

I am trying to compile this code locally and see if I can help out. I am thinking of moving the dependencies to the latest versions supported in fs2 v2 and then try to migrate them to v3.
Please provide feedback or any suggestions you might have.

**Comment by regis-leray** [comment]
if you can submit a PR go for it. but im planning  to do it :)

**Comment by rehanone** [comment]
Thanks @regis-leray , I have given it a try #132 . I am still not fully up to speed with new Cats Effect IO Type system so I i have done what I understood to be the best way to migrate.
 Please provide your feedback.

**Comment by regis-leray** [comment]
blabla
