### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by rlavolee** [regis-leray/fs2-ftp#318]
## 🦶 What I did? steps by step 

`sbt test`

## 🆘 Problem OR Log error 

`javax.net.ssl.SSLHandshakeException: NotAfter: Wed Apr 24 08:36:56 CEST 2024`

## 🤔 Expectation

running tests successfully

## 📝 notes

pure-ftpd.pem has expired. Do you want me to add a new one in a PR ? 
Do you plan to merge scala-steward PRs ?

**Comment by rlavolee** [comment]
Hi @regis-leray  ! 

Did you have time to take a look at my issue ?

Regards

**Comment by regis-leray** [comment]
sorry it is fixed now
