### ISSUE TITLE
`Publish Artifacts` job failed

### ISSUE THREAD

**Issue by rlavolee** [regis-leray/fs2-ftp#334]
Hi @regis-leray !

I'm sorry to bother you again but It seems that the Publish Artifacts job is failing due to network issue I suppose 🤔 .
Would you have time to take a look at this issue ?

Regards,
Rémi

PS: if solved will you consider to publish a new fs2-ftp version ?

**Comment by regis-leray** [comment]
this is due to the expired key

**Comment by rlavolee** [comment]
Thank you very much ! 🙏
