### ISSUE TITLE
Configure timeout for sftp/ftp connections

### ISSUE THREAD

**Issue by gpintore82** [regis-leray/fs2-ftp#50]
Hi @regis-leray,
Didn't found a way to configure the timeout for the connection. Is there any way of doing something like that?
Thanks!

**Comment by regis-leray** [comment]
At this moment, there is no way to setup a timeOut, and the default value is 0.
So it will be define by ftp server configuration.

You can create PR, if neeeded

**Comment by regis-leray** [comment]
i released a new version https://github.com/regis-leray/fs2-ftp/releases/tag/v0.6.2
with support of timeout thank for the reporting
